# Generated by Django 2.2.1 on 2019-05-20 08:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 5, 20, 11, 0, 1, 343027))),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 5, 20, 11, 0, 1, 343027))),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Part')),
            ],
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.AddField(
            model_name='part',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Section'),
        ),
        migrations.AddField(
            model_name='answer',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Thread'),
        ),
    ]
